{% set version = "3.7.3" %}
{% set build = 1 %}

package:
  name: arrayfire-cuda
  version: {{ version }}

source:
    git_url: https://github.com/arrayfire/arrayfire
    git_rev: v{{ version }}

build:      
  number: {{ build }}
  script_env:
    - ENABLE_CUDA=ON  # [ cuda_compiler_version != "None" ] 
    - ENABLE_CUDA=OFF # [ cuda_compiler_version == "None" ] 
    - ENABLE_CPU=OFF  # [ cuda_compiler_version != "None" ] 
    - ENABLE_CPU=ON   # [ cuda_compiler_version == "None" ] 

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }} # [ cuda_compiler_version != "None" ]
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - cudnn {{ cudnn }} # [ cuda_compiler_version != "None" ]
    - mkl               # [ cuda_compiler_version == "None" ]
    - boost
    - fftw
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [ cuda_compiler_version != "None" ]
    - {{ pin_compatible('cudnn') }}  # [ cuda_compiler_version != "None" ]
    - {{ pin_compatible('mkl') }}    # [ cuda_compiler_version == "None" ]
    - fftw

about:
  home: http://arrayfire.org/
  license_file:
    - LICENSE
  summary: 'ArrayFire is a high performance software library for parallel computing with an easy-to-use API. Its array based function set makes parallel programming more accessible.'

extra:
  recipe-maintainers: 
    - tvandera
