{% set version = "3.7.3" %}
{% set build = 1 %}

package:
  name: arrayfire
  version: {{ version }}

source:
    git_url: https://github.com/arrayfire/arrayfire
    git_rev: v{{ version }}
    patches:
      - 0001-FIX-fix-compilation-on-windows-when-libiomp5.lib-par.patch

build:      
  number: {{ build }}
  script_env:
    - ENABLE_CUDA=ON  # [ cuda_compiler_version != "None" ] 
    - ENABLE_CUDA=OFF # [ cuda_compiler_version == "None" ] 
    - ENABLE_CPU=OFF  # [ cuda_compiler_version != "None" ] 
    - ENABLE_CPU=ON   # [ cuda_compiler_version == "None" ] 
  ignore_run_exports_from:
    - cudnn # cudnn is loaded as a plugin

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }} # [ cuda_compiler_version != "None" ]
    - cmake
  host:
    - cudnn {{ cudnn }}              # [ cuda_compiler_version != "None" ]
    - mkl-devel                      # [ cuda_compiler_version == "None" ]
    - intel-openmp                   # [ cuda_compiler_version == "None" ]
    - boost
    - fftw
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [ cuda_compiler_version != "None" ]
    - {{ pin_compatible('cudnn') }}  # [ cuda_compiler_version != "None" ]
    - {{ pin_compatible('mkl') }}    # [ cuda_compiler_version == "None" ]
    - {{ pin_compatible('intel-openmp') }}    # [ cuda_compiler_version == "None" ]
    - fftw

about:
  home: http://arrayfire.org/
  license_file:
    - LICENSE
  summary: 'ArrayFire is a high performance software library for parallel computing with an easy-to-use API. Its array based function set makes parallel programming more accessible.'

extra:
  recipe-maintainers: 
    - tvandera
