package:
  name: arrayfire-gpu
  version: "3.7.3"

build:      
  number: 4

source:
    git_url: https://github.com/arrayfire/arrayfire
    git_rev: v3.7.3

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
  host:
    - cudatoolkit {{ cudatoolkit }}*
    - cudnn {{ cudnn }}*
    - boost
    - fftw
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - {{ pin_compatible('cudnn') }}      
    - fftw

about:
  home: http://arrayfire.org/
  license: Open Source
  summary: 'ArrayFire is a high performance software library for parallel computing with an easy-to-use API. Its array based function set makes parallel programming more accessible.'
